name: Publish README to GitHub Pages

on:
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy README.md to index.md
        run: cp README.md index.md

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch the action should deploy to.
          folder: .  # The folder the action should deploy.
          single-commit: true
          commit-message: "Deploy README.md markdown to GitHub Pages"
